[package]
name = "encoding-asn1-derive"
version = "0.1.0"
edition = "2018"

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["extra-traits"] }
quote = "1.0"
proc-macro-error = "1.0.0"

[lib]
proc-macro = true